name: Man10Score
version: 1.0
softdepend:
  - Man10CommonLibs
main: red.man10.man10score.Man10Score
api-version: 1.16
commands:
  score:
    default: op
    permission: man10score.user
  mscore:
    default: op
    permission: man10score.op
  thank:
    default: op
    permission: man10score.user
  fuck:
    default: op
    permission: man10score.user